- _target_: geomstats.geometry.with_boundary.polytope.Polytope
  npz: ${npz}
  metric_type: ${metric_type}
  eps: ${p_eps}
- _target_: geomstats.geometry.product_manifold.ProductSameManifold
  manifold:
    _target_: geomstats.geometry.hypersphere.Hypersphere
    dim: 1
  mul: ${n_torus}
  default_point_type: vector